Hexlet tasks
snoskova07/php_hexlet pull request #1
Opened 2022-06-16 09:16 UTC by snoskova07

2022-06-17 07:13 UTC, ova777 commented on Brackets.php
> +function isBalanced($string) {
Открывающая скобка должна быть на новой строке

2022-06-17 13:51 UTC, ovaunit requested changes

2022-06-17 13:51 UTC, ovaunit commented on Brackets.php
> +function isBalanced($string)
Функция должна возвращать bool (true или false)

2022-06-17 13:51 UTC, ova777 commented on Brackets.php
> +        if ($string[0] === ')' || $string[$lengthOfString - 1] === '(') {
Зачем эта проверка внутри цикла? если скобки корректные - проверка происходит при каждой итерации

2022-06-17 13:51 UTC, ova777 commented on Brackets.php
> +            $open = $open + 1;
Здесь можно использовать короткую запись: `$open += 1` (ниже для $close тоже)

2022-06-17 13:51 UTC, ovaunit commented on Brackets.php
> +    else {
Не по PSR

2022-06-17 13:51 UTC, ovaunit commented on Ticket.php
> +function isHappy($ticket)
По условию задачи функция должна возвращать bool (true или false)

2022-06-17 13:51 UTC, ova777 commented on Ticket.php
> +              $sum1 = $sum1 + $ticket[$i];
Здесь можно использовать короткую запись: `$sum1 += $ticket[$i]`

2022-06-17 13:51 UTC, ova777 commented on Ticket.php
> +          for ($i = $iterations; $i < strlen($ticket); $i++) {
strlen вычисляется на каждой итерации, хотя $ticket у нас не меняется

2022-06-17 13:51 UTC, ova777 commented on Ticket.php
> +              $sum2 = $sum2 + $ticket[$i];
Здесь можно использовать короткую запись: `$sum2 += $ticket[$i]`

2022-06-17 13:51 UTC, ova777 commented on addDigits.php
> +function addDigits($chislo)
По условию задачи функция должна возвращать чисто, а не выводить результат в stdout

2022-06-17 13:51 UTC, ova777 commented on addDigits.php
> +        for ($i = 0; $i < strlen($str); $i++) {
strlen вычисляется на каждой итерации, хотя $str у нас не меняется

2022-06-17 13:51 UTC, ova777 commented on addDigits.php
> +            $sum = $sum + (integer)$str[$i];
Здесь можно использовать короткую запись: `$sum += (integer)$str[$i]`

2022-06-17 13:51 UTC, ova777 commented on binarySum.php
> +function binarySum ($a, $b)
После названия функции пробел не нужен

2022-06-17 13:51 UTC, ova777 commented on binarySum.php
> +    $sum_dec = bindec($a) + bindec($b);
По PSR переменные должны называться в camelCase

2022-06-17 13:51 UTC, ova777 commented on fib.php
> +function fib($number)
В задании не сказано что функция должна возвращать результат (а не выводить его), но все же лучше сделать функцию чистой

2022-06-17 13:51 UTC, ova777 commented on fizzBuzz.php
> +function fizzBuzz($begin, $end)
У тебя при выводе результата между элементами получаются двойные пробелы, а должны быть одинарные

2022-06-17 13:51 UTC, ova777 commented on fizzBuzz.php
> +            print_r(" FizzBuzz ");
Зачем здесь текст в двойных кавычках? В нем ведь нет переменных, в таком случае лучше в одинарных (ниже аналогично)

2022-06-17 13:51 UTC, ova777 commented on isPerfect.php
> +function isPerfect($number)
По условию задачи функция должна возвращать bool (true или false)

2022-06-17 13:51 UTC, ova777 commented on isPerfect.php
> +            $sum = $sum + $i;
Здесь можно использовать короткую запись: `$sum += $i`

2022-06-17 13:51 UTC, ova777 commented on isPowerOfThree.php
> +function isPowerOfThree($num)
Здесь по заданию имелось виду что функция должна возвращать bool (true или false)

2022-06-17 13:51 UTC, ova777 commented on isPowerOfThree.php
> +        $num = $num / 3;
Здесь можно использовать короткую запись: `$num /= 3`

2022-06-17 13:51 UTC, ova777 commented on isPowerOfThree.php
> +        $i = $i + 1;
Здесь тоже можно использовать короткую запись: `$i += 1;`, а лучше просто `$i++;`

2022-06-17 14:54 UTC, snoskova07 commented on addDigits.php
> +        for ($i = 0; $i < strlen($str); $i++) {
Там длина строки уменьшается

2022-06-17 14:55 UTC, snoskova07 commented on binarySum.php
> +function binarySum ($a, $b)
ok

2022-06-17 14:56 UTC, snoskova07 commented on binarySum.php
> +    $sum_dec = bindec($a) + bindec($b);
ok

2022-06-17 14:57 UTC, snoskova07 commented on fib.php
> +function fib($number)
ok

2022-06-17 15:04 UTC, snoskova07 commented on fizzBuzz.php
> +            print_r(" FizzBuzz ");
ok

2022-06-17 15:05 UTC, snoskova07 commented on isPerfect.php
> +function isPerfect($number)
ok

2022-06-17 15:07 UTC, snoskova07 commented on isPowerOfThree.php
> +function isPowerOfThree($num)
ok

2022-06-17 15:07 UTC, snoskova07 commented on isPowerOfThree.php
> +        $num = $num / 3;
ok

2022-06-17 15:08 UTC, snoskova07 commented on isPowerOfThree.php
> +        $i = $i + 1;
ok

2022-06-17 15:08 UTC, snoskova07 commented on Brackets.php
> +        if ($string[0] === ')' || $string[$lengthOfString - 1] === '(') {
логично

2022-06-17 15:08 UTC, snoskova07 commented on Brackets.php
> +            $open = $open + 1;
ok

2022-06-17 15:09 UTC, snoskova07 commented on Ticket.php
> +function isHappy($ticket)
ok

2022-06-17 15:09 UTC, snoskova07 commented on Ticket.php
> +              $sum1 = $sum1 + $ticket[$i];
ok

2022-06-17 15:09 UTC, snoskova07 commented on Ticket.php
> +          for ($i = $iterations; $i < strlen($ticket); $i++) {
ok

2022-06-17 15:10 UTC, snoskova07 commented on addDigits.php
> +function addDigits($chislo)
ok

2022-06-17 15:10 UTC, snoskova07 commented on addDigits.php
> +            $sum = $sum + (integer)$str[$i];
ok

2022-06-17 15:35 UTC, snoskova07 commented on fizzBuzz.php
> +function fizzBuzz($begin, $end)
ok

2022-06-17 15:36 UTC, snoskova07 commented on Brackets.php
> +function isBalanced($string)
ok

2022-06-17 16:23 UTC, merged

2022-06-21 11:50 UTC, RuslanTyan commented on fizzBuzz.php
> +            $result .= 'Bazz ';
Buzz ?